
version: '2.1'
services:
  # data container provide plugins
  base-sonarqube-plugins:
    build: sonarqube-plugins
    image: ${IMAGE_PREFIX:-cirepo}/sonarqube-plugins:${IMAGE_TAG:-6.7.3-alpine}
  base-sonarqube:
    build: sonarqube
    environment:
    # mysql.local
    - SONARQUBE_JDBC_URL=${SONARQUBE_JDBC_URL:-jdbc:mysql://mysql.local:3306/sonar?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useConfigs=maxPerformance}
    - SONARQUBE_JDBC_USERNAME=${SONARQUBE_JDBC_USERNAME:-sonar}
    - SONARQUBE_JDBC_PASSWORD=${SONARQUBE_JDBC_PASSWORD:-sonar}
    image: ${IMAGE_PREFIX:-cirepo}/sonarqube:${IMAGE_TAG:-6.7.3-alpine}
    restart: always
