version: '2.1'
services:
  sonarqube:
    extends:
      file: docker-compose-base.yml
      service: base-sonarqube
    networks:
      local-network:
        ipv4_address: ${IPV4_ADDRESS:-172.16.238.67}
        #ipv6_address: ${IPV6_ADDRESS:-2001:3984:3989::67}
    ports:
    - "${EXTERNAL_SONARQUBE_9000_PORT:-9000}:9000"
    - "${EXTERNAL_SONARQUBE_9092_PORT:-9092}:9092"
    volumes:
    - data:/opt/sonarqube/data

networks:
  local-network:
    external: true
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
      #- subnet: 2001:3984:3989::/64

volumes:
  data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/data
      o: bind
