
version: '2.1'
services:
  # data container provide plugins
  base-sonarqube-plugins:
    build: sonarqube-plugins
    image: ${IMAGE_PREFIX:-cirepo/}sonarqube-plugins:${IMAGE_TAG:-6.7.3-alpine}
  base-sonarqube:
    build: sonarqube
    environment:
    # mysql56
    - SONARQUBE_JDBC_URL=${SONARQUBE_JDBC_URL:-jdbc:mysql://mysql56:3306/sonar?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useConfigs=maxPerformance}
    - SONARQUBE_JDBC_USERNAME=${SONARQUBE_JDBC_USERNAME:-sonar}
    - SONARQUBE_JDBC_PASSWORD=${SONARQUBE_JDBC_PASSWORD:-sonar}
    image: ${IMAGE_PREFIX:-cirepo/}sonarqube:${IMAGE_TAG:-6.7.3-alpine}
    labels:
      deploy.config.commit: ${LABEL_DEPLOY_CONFIG_COMMIT:-unknown}
      deploy.config.name: ${LABEL_DEPLOY_CONFIG_NAME:-unknown}
      deploy.config.ref: ${LABEL_DEPLOY_CONFIG_REF:-unknown}
      deploy.util.commit: ${LABEL_DEPLOY_UTIL_COMMIT:-unknown}
      deploy.util.ref: ${LABEL_DEPLOY_UTIL_REF:-unknown}
      instance.name.short: ${LABEL_INSTANCE_NAME_SHORT:-standalone.sonarqube}
      instance.name: ${LABEL_INSTANCE_NAME:-127.0.0.1/sonarqube/standalone}
    restart: always
