
version: '2.1'
services:
  # data container provide plugins
  sonarqube-plugins-develop:
    extends:
      file: docker-compose-base.yml
      service: base-sonarqube-plugins
    container_name: ${INSTANCE_NAME:-sonarqube}-plugins.${INSTANCE_DOMAIN:-local}
  sonarqube-develop:
    extends:
      file: docker-compose-base.yml
      service: base-sonarqube
    container_name: ${INSTANCE_NAME:-sonarqube}.${INSTANCE_DOMAIN:-local}
    hostname: ${INSTANCE_NAME:-sonarqube}.${INSTANCE_DOMAIN:-local}
    networks:
      local-network:
        ipv4_address: 172.16.238.67
        ipv6_address: 2001:3984:3989::67
    ports:
    - "${SONARQUBE_EXTERNAL_PORT:-9000}:${SONARQUBE_PORT:-9000}"
    #- "9092:9092"
    volumes:
    #- conf:/opt/sonarqube/conf
    - data:/opt/sonarqube/data
    #- extensions:/opt/sonarqube/extensions
    #- bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    volumes_from:
    - sonarqube-plugins-develop

networks:
  local-network:
    external: true
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
      - subnet: 2001:3984:3989::/64

volumes:
  data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/data
      o: bind
